SELECT document_name,
  document_id,
  timestamp,
  operation,
  JSON_EXTRACT_SCALAR(data, '$.due') AS DUE,
  JSON_EXTRACT_SCALAR(data, '$.method') AS METHOD,
  JSON_EXTRACT_SCALAR(data, '$.bankBenefeciaryName') AS BANKBENEFECIARYNAME,
  JSON_EXTRACT_SCALAR(data, '$.bankAccount') AS BANKACCOUNT,
  JSON_EXTRACT_SCALAR(data, '$.bankName') AS BANKNAME,
  JSON_EXTRACT_SCALAR(data, '$.bankSwiftCode') AS BANKSWIFTCODE,
  JSON_EXTRACT_SCALAR(data, '$.intermediaryBankName') AS INTERMEDIARYBANKNAME,
  JSON_EXTRACT_SCALAR(data, '$.intermediaryBankSwiftCode') AS INTERMEDIARYBANKSWIFTCODE,
  JSON_EXTRACT_SCALAR(data, '$.intermediaryBankAba') AS INTERMEDIARYBANKABA,
  JSON_EXTRACT_SCALAR(data, '$.achBenefeciaryName') AS ACHBENEFECIARYNAME,
  JSON_EXTRACT_SCALAR(data, '$.achRoutingNumber') AS ACHROUTINGNUMBER,
  JSON_EXTRACT_SCALAR(data, '$.achAccountNumber') AS ACHACCOUNTNUMBER,
  JSON_EXTRACT_SCALAR(data, '$.achType') AS ACHTYPE,
  JSON_EXTRACT_SCALAR(data, '$.achBankAddress') AS ACHBANKADDRESS,
  JSON_EXTRACT_SCALAR(data, '$.payoneerEmail') AS PAYONEEREMAIL,
  JSON_EXTRACT_SCALAR(data, '$.payoneerAccount') AS PAYONEERACCOUNT,
  JSON_EXTRACT_SCALAR(data, '$.paypalEmail') AS PAYPALEMAIL,
  JSON_EXTRACT_SCALAR(data, '$.paypalAccount') AS PAYPALACCOUNT,
  JSON_EXTRACT_SCALAR(data, '$.paypalMobile') AS PAYPALMOBILE,
  JSON_EXTRACT_SCALAR(data, '$.cardNumber') AS CARDNUMBER,
  JSON_EXTRACT_SCALAR(data, '$.cardOwner') AS CARDOWNER,
  JSON_EXTRACT_SCALAR(data, '$.user') AS USER
FROM `invoicemaker-f5e1d.firestore_export.paymentsSettings_raw_changelog`